name: Roberto Giacomolli
favicon: null
layout_spectrum: 0.6110152613837272
typography_spectrum: 0.595554472412914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9442861147690564
  lightness: 0.44033224205486476
  saturation: 0.28124317340552807
  rhythmicContrast: 0.7835368430241942
purpose: []
